<?php

return array (
  'name' => '诚正数藏',
  'beian' => '赣ICP备2022005980号',
  'cdnurl' => '',
  'version' => '1.0.5',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'dashboard',
  'categorytype' => 
  array (
    'default' => '默认',
    'page' => '单页',
    'article' => '文章',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => '基础配置',
    'dictionary' => '字典配置',
    'contents' => '文本协议',
    'Ali' => '支付宝配置',
    'Wx' => '微信配置',
    'contact' => '联系我们',
    'goods' => '藏品设置',
    'compose' => '合成配置',
    'beckoning' => '阿里云身份证手机号姓名验证',
    'wenchangchain' => '文昌链配置',
    'timeconfiguration' => '优先购时间配置',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '1129205956@qq.com',
  'mail_smtp_pass' => 'dpauixlvnlwqicff',
  'mail_verify_type' => '2',
  'mail_from' => '1129205956@qq.com',
  'attachmentcategory' => 
  array (
    'category1' => '分类一',
    'category2' => '分类二',
    'custom' => '自定义',
  ),
  'default_image' => 
  array (
    0 => '/uploads/20220817/8830fddf33df7e3feb1806be1e7fe663.png',
  ),
  'users_content' => '<div><p class="MsoNormal" style="text-indent:44.0000pt;mso-char-indent-count:2.0000;"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">在此特别提醒您（用户）在注册成为用户之前，请认真阅读本《用户协议》（以下简称</span></font><font face="Calibri"><span style="font-size: 18px;">“</span></font><font face="宋体"><span style="font-size: 18px;">协议</span></font><font face="Calibri"><span style="font-size: 18px;">”</span></font><font face="宋体"><span style="font-size: 18px;">），确保您充分理解本协议中各条款。请您审慎阅读并选择接受或不接受本协议。您的注册、登录、使用等行为将视为对本协议的接受，并同意接受本协议各项条款的约束。本协议约定</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">宜春藏文网络</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">科技有限公司（以下简称</span></font><font face="Calibri"><span style="font-size: 18px;">“</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">藏文</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="Calibri"><span style="font-size: 18px;">”</span></font><font face="宋体"><span style="font-size: 18px;">）与用户之间关于</span></font><font face="Calibri"><span style="font-size: 18px;">“</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="Calibri"><span style="font-size: 18px;">”</span></font><font face="宋体"><span style="font-size: 18px;">软件服务（以下简称</span></font><font face="Calibri"><span style="font-size: 18px;">“</span></font><font face="宋体"><span style="font-size: 18px;">服务</span></font><font face="Calibri"><span style="font-size: 18px;">“</span></font><font face="宋体"><span style="font-size: 18px;">）的权利义务。</span></font><font face="Calibri"><span style="font-size: 18px;">“</span></font><font face="宋体"><span style="font-size: 18px;">用户</span></font><font face="Calibri"><span style="font-size: 18px;">”</span></font><font face="宋体"><span style="font-size: 18px;">是指注册、登录、使用本服务的个人。本协议可由</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">随时更新，更新后的协议条款一旦公布即代替原来的协议条款，恕不再另行通知，用户可在本</span></font><span style="font-size: 18px;">APP</span><font face="宋体"><span style="font-size: 18px;">中查阅最新版协议条款。在修改协议条款后，如果用户不接受修改后的条款，请立即停止使用</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">藏文</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">提供的服务，用户继续使用服务将被视为接受修改后的协议。</span></font><span style="font-size: 18px;"> &nbsp;</span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;text-indent:0.0000pt;
mso-char-indent-count:0.0000;mso-list:l5 level1 lfo1;"><!--[if !supportLists]--><span style="font-family: 宋体; font-size: 18px;">一、</span><!--[endif]--><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">账号注册</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;mso-list:l1 level1 lfo2;"><!--[if !supportLists]--><span style="font-family: Calibri; font-size: 18px;">1、</span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">用户在使用本服务前需要注册一个</span></font><font face="Calibri"><span style="font-size: 18px;">“</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="Calibri"><span style="font-size: 18px;">”</span></font><font face="宋体"><span style="font-size: 18px;">账号。</span></font><font face="Calibri"><span style="font-size: 18px;">“</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="Calibri"><span style="font-size: 18px;">”</span></font><font face="宋体"><span style="font-size: 18px;">账号应当使用手机号码绑定注册，请用户使用尚未与</span></font><font face="Calibri"><span style="font-size: 18px;">“</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="Calibri"><span style="font-size: 18px;">”</span></font><font face="宋体"><span style="font-size: 18px;">账号绑定的手机号码，以及未被服务根据本协议封禁的手机号码注册</span></font><font face="Calibri"><span style="font-size: 18px;">“</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="Calibri"><span style="font-size: 18px;">”</span></font><font face="宋体"><span style="font-size: 18px;">账号。服务可以根据用户需求或产品需要对账号注册和绑定的方式进行变更，而无须事先通知用户。 </span></font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;mso-list:l1 level1 lfo2;"><!--[if !supportLists]--><span style="font-family: Calibri; font-size: 18px;">2、</span><!--[endif]--><span style="font-family: Calibri; font-size: 18px;"><font face="Calibri">“</font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="Calibri"><span style="font-size: 18px;">”</span></font><font face="宋体"><span style="font-size: 18px;">系基于</span></font><font face="Calibri"><span style="font-size: 18px;">“</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">藏文</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="Calibri"><span style="font-size: 18px;">“</span></font><font face="宋体"><span style="font-size: 18px;">的</span></font><font face="Calibri"><span style="font-size: 18px;">APP</span></font><font face="宋体"><span style="font-size: 18px;">产品，用户注册时应当授权</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">及使用其个人信息方可成功注册</span></font><font face="Calibri"><span style="font-size: 18px;">“</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="Calibri"><span style="font-size: 18px;">”</span></font><font face="宋体"><span style="font-size: 18px;">账号。故用户完成注册即表明用户同意服务提取、公开及使用用户的信息。 </span></font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;mso-list:l1 level1 lfo2;"><!--[if !supportLists]--><span style="font-family: Calibri; font-size: 18px;">3、</span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">鉴于</span></font><font face="Calibri"><span style="font-size: 18px;">“</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="Calibri"><span style="font-size: 18px;">”</span></font><font face="宋体"><span style="font-size: 18px;">账号的绑定注册方式，您同意服务在注册时将允许您的手机号码及手机设备识别码等信息用于注册。 </span></font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;mso-list:l1 level1 lfo2;"><!--[if !supportLists]--><span style="font-family: Calibri; font-size: 18px;">4、</span><!--[endif]--><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">在用户注册及使用本服务时，</font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">需要搜集能识别用户身份的个人信息以便服务可以在必要时联系用户，或为用户提供更好的使用体验。</font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">搜集的信息包括但不限于用户的姓名、地址；</font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">同意对这些信息的使用将受限于第三条用户个人隐私信息保护的约束。</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;text-indent:0.0000pt;
mso-char-indent-count:0.0000;mso-list:l5 level1 lfo1;"><!--[if !supportLists]--><span style="font-family: 宋体; font-size: 18px;">二、</span><!--[endif]--><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">用户个人隐私信息保护</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;mso-list:l8 level1 lfo3;"><!--[if !supportLists]--><span style="font-family: Calibri; font-size: 18px;">1、</span><!--[endif]--><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">如果</font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">发现或收到他人举报或投诉用户违反本协议约定的，</font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">有权不经通知随时对相关内容，包括但不限于用户资料、发贴记录进行审查、删除，并视情节轻重对违规账号处以包括但不限于警告、账号封禁</span></font><span style="font-size: 18px;"> </span><font face="宋体"><span style="font-size: 18px;">、设备封禁</span></font><span style="font-size: 18px;"> </span><font face="宋体"><span style="font-size: 18px;">、功能封禁</span></font><span style="font-size: 18px;"> </span><font face="宋体"><span style="font-size: 18px;">的处罚，且通知用户处理结果。</span></font><span style="font-size: 18px;"> </span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;mso-list:l8 level1 lfo3;"><!--[if !supportLists]--><span style="font-family: Calibri; font-size: 18px;">2、</span><!--[endif]--><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">因违反用户协议被封禁的用户，可以自行与</font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">联系。其中，被实施功能封禁的用户会在封禁期届满后自动恢复被封禁功能。被封禁用户可提交申诉，</font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">将对申诉进行审查，并自行合理判断决定是否变更处罚措施。</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;text-indent:0.0000pt;
mso-char-indent-count:0.0000;mso-list:l8 level1 lfo3;"><!--[if !supportLists]--><span style="font-family: Calibri; font-size: 18px;">3、</span><!--[endif]--><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">用户理解并同意，</font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">有权依合理判断对违反有关法律法规或本协议规定的行为进行处罚，对违法违规的任何用户采取适当的法律行动，并依据法律法规保存有关信息向有关部门报告等，用户应承担由此而产生的一切法律责任。</span></font><span style="font-size: 18px;"> </span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;text-indent:0.0000pt;
mso-char-indent-count:0.0000;mso-list:l8 level1 lfo3;"><!--[if !supportLists]--><span style="font-family: Calibri; font-size: 18px;">4、</span><!--[endif]--><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">用户理解并同意，因用户违反本协议约定，导致或产生的任何第三方主张的任何索赔、要求或损失，包括合理的律师费，用户应当赔偿</font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">与合作公司、关联公司，并使之免受损害。</span></font><span style="font-size: 18px;"> </span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;text-indent:0.0000pt;
mso-char-indent-count:0.0000;mso-list:l5 level1 lfo1;"><!--[if !supportLists]--><span style="font-family: 宋体; font-size: 18px;">三、</span><!--[endif]--><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">用户发布内容规范</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;mso-list:l6 level1 lfo4;"><!--[if !supportLists]--><span style="font-family: Calibri; font-size: 18px;">1、</span><!--[endif]--><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">本条所述内容是指用户使用服务的过程中所制作、上载、复制、发布、传播的任何内容，包括但不限于账号头像、名称、用户说明等注册信息及认证资料，或文字、语音、图片、视频、图文等发送、回复或自动回复消息和相关链接页面，以及其他使用账号或本服务所产生的内容。</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;mso-list:l6 level1 lfo4;"><!--[if !supportLists]--><span style="font-family: Calibri; font-size: 18px;">2、</span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">用户不得利用</span></font><font face="Calibri"><span style="font-size: 18px;">“</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="Calibri"><span style="font-size: 18px;">”</span></font><font face="宋体"><span style="font-size: 18px;">账号或本服务制作、上载、复制、发布、传播如下法律、法规和政策禁止的内容：</span></font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;text-indent:0.0000pt;
mso-char-indent-count:0.0000;mso-list:l2 level1 lfo5;"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(1)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">反对宪法所确定的基本原则的；</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;text-indent:0.0000pt;
mso-char-indent-count:0.0000;mso-list:l2 level1 lfo5;"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(2)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">危害国家安全，泄露国家秘密，颠覆国家政权，破坏国家统一的；</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;text-indent:0.0000pt;
mso-char-indent-count:0.0000;mso-list:l2 level1 lfo5;"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(3)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">损害国家荣誉和利益的；</span></font><span style="font-size: 18px;"> </span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;text-indent:0.0000pt;
mso-char-indent-count:0.0000;mso-list:l2 level1 lfo5;"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(4)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">煽动民族仇恨、民族歧视，破坏民族团结的；</span></font><span style="font-size: 18px;"> </span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;text-indent:0.0000pt;
mso-char-indent-count:0.0000;mso-list:l2 level1 lfo5;"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(5)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">破坏国家宗教政策，宣扬邪教和封建迷信的；</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;text-indent:0.0000pt;
mso-char-indent-count:0.0000;mso-list:l2 level1 lfo5;"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(6)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">散布谣言，扰乱社会秩序，破坏社会稳定的；</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;text-indent:0.0000pt;
mso-char-indent-count:0.0000;mso-list:l2 level1 lfo5;"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(7)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">散布淫秽、色情、赌博、暴力、凶杀、恐怖或者教唆犯罪的；</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;text-indent:0.0000pt;
mso-char-indent-count:0.0000;mso-list:l2 level1 lfo5;"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(8)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">侮辱或者诽谤他人，侵害他人合法权益的；</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;text-indent:0.0000pt;
mso-char-indent-count:0.0000;mso-list:l2 level1 lfo5;"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(9)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">含有法律、行政法规禁止的其他内容的信息。</span></font><span style="font-size: 18px;"> </span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;text-indent:0.0000pt;
mso-char-indent-count:0.0000;mso-list:l6 level1 lfo4;"><!--[if !supportLists]--><span style="font-family: Calibri; font-size: 18px;">3、</span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">用户不得利用</span></font><font face="Calibri"><span style="font-size: 18px;">“</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="Calibri"><span style="font-size: 18px;">”</span></font><font face="宋体"><span style="font-size: 18px;">账号或本服务制作、上载、复制、发布、传播如下干扰</span></font><font face="Calibri"><span style="font-size: 18px;">“</span></font><font face="宋体"><span style="font-size: 18px;">服务</span></font><font face="Calibri"><span style="font-size: 18px;">”</span></font><font face="宋体"><span style="font-size: 18px;">正常运营，以及侵犯其他用户或第三方合法权益的内容：</span></font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;mso-list:l0 level1 lfo6;"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(1)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">含有任何性或性暗示的；</span></font><span style="font-size: 18px;"> </span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;mso-list:l0 level1 lfo6;"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(2)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">含有辱骂、恐吓、威胁内容的；</span></font><span style="font-size: 18px;"> </span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;mso-list:l0 level1 lfo6;"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(3)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">含有骚扰、垃圾广告、恶意信息、诱骗信息的；</span></font><span style="font-size: 18px;"> </span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;mso-list:l0 level1 lfo6;"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(4)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">涉及他人隐私、个人信息或资料的；</span></font><span style="font-size: 18px;"> </span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;mso-list:l0 level1 lfo6;"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(5)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">侵害他人名誉权、肖像权、知识产权、商业秘密等合法权利的；</span></font><span style="font-size: 18px;"> </span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;mso-list:l0 level1 lfo6;"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(6)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">含有其他干扰本服务正常运营和侵犯其他用户或第三方合法权益内容的信息。</span></font><span style="font-size: 18px;"> &nbsp;</span><font face="宋体"><span style="font-size: 18px;">四、使用规则</span></font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><!--[if !supportLists]--><span style="font-family: Calibri; font-size: 18px;">1、</span><!--[endif]--><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">用户在本服务中或通过本服务所传送、发布的任何内容并不反映或代表，也不得被视为反映或代表</font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">的观点、立场或政策，</font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">对此不承担任何责任。</span></font><span style="font-size: 18px;"> </span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><!--[if !supportLists]--><span style="font-family: Calibri; font-size: 18px;">2、</span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">用户不得利用</span></font><font face="Calibri"><span style="font-size: 18px;">“</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="Calibri"><span style="font-size: 18px;">”</span></font><font face="宋体"><span style="font-size: 18px;">账号或本服务进行如下行为：</span></font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(1)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">提交、发布虚假信息，或盗用他人头像或资料，冒充、利用他人名义的；</span></font><span style="font-size: 18px;"> </span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(2)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">强制、诱导其他用户关注、点击链接页面或分享信息的；</span></font><span style="font-size: 18px;"> </span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(3)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">虚构事实、隐瞒真相以误导、欺骗他人的；</span></font><span style="font-size: 18px;"> </span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(4)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">利用技术手段批量建立虚假账号的；</span></font><span style="font-size: 18px;"> </span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(5)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">利用</span></font><font face="Calibri"><span style="font-size: 18px;">“</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="Calibri"><span style="font-size: 18px;">”</span></font><font face="宋体"><span style="font-size: 18px;">账号或本服务从事任何违法犯罪活动的； </span></font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(6)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">制作、发布与以上行为相关的方法、工具，或对此类方法、工具进行运营或传播，无论这些行为是否为商业目的；</span></font><span style="font-size: 18px;"> </span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><!--[if !supportLists]--><span style="font-family:Calibri;mso-fareast-font-family:宋体;mso-bidi-font-family:\'Times New Roman\';
font-size:22.0000pt;mso-font-kerning:1.0000pt;"><span style="font-size: 18px;">(7)</span><span style="font-size: 18px;">&nbsp;</span></span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">其他违反法律法规规定、侵犯其他用户合法权益、干扰</span></font><font face="Calibri"><span style="font-size: 18px;">“</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="Calibri"><span style="font-size: 18px;">”</span></font><font face="宋体"><span style="font-size: 18px;">正常运营或服务未明示授权的行为。 </span></font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:0.0000pt;mso-para-margin-left:0.0000gd;text-indent:0.0000pt;
mso-char-indent-count:0.0000;mso-list:l3 level1 lfo7;"><!--[if !supportLists]--><span style="font-family: Calibri; font-size: 18px;">3、</span><!--[endif]--><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">用户须对利用</span></font><font face="Calibri"><span style="font-size: 18px;">“</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="Calibri"><span style="font-size: 18px;">”</span></font><font face="宋体"><span style="font-size: 18px;">账号或本服务传送信息的真实性、合法性、无害性、准确性、有效性等全权负责，与用户所传播的信息相关的任何法律责任由用户自行承担，与</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">无关。</span></font><span style="font-size: 18px;"> </span><font face="宋体"><span style="font-size: 18px;">如因此给</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">或第三方造成损害的，用户应当依法予以赔偿。</span></font><span style="font-size: 18px;"> </span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:0.0000pt;mso-para-margin-left:0.0000gd;text-indent:0.0000pt;
mso-char-indent-count:0.0000;mso-list:l3 level1 lfo7;"><!--[if !supportLists]--><span style="font-family: 宋体; font-size: 18px;">4、</span><!--[endif]--><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">提供的服务中可能包括广告，用户同意在使用过程中显示</font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">和第三方供应商、合作伙伴提供的广告。除法律法规明确规定外，用户应自行对依该广告信息进行的交易负责，</span></font><span style="font-size: 18px;"> </span><font face="宋体"><span style="font-size: 18px;">对用户因依该广告信息进行的交易或前述广告商提供的内容而遭受的损失或损害，</span></font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">不承担任何责任。</span></font><span style="font-size: 18px;"> &nbsp;</span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;text-indent:0.0000pt;
mso-char-indent-count:0.0000;mso-list:l5 level1 lfo1;"><!--[if !supportLists]--><span style="font-family: 宋体; font-size: 18px;">四、</span><!--[endif]--><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">其他</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;mso-list:l4 level1 lfo9;"><!--[if !supportLists]--><span style="font-family: 宋体; font-size: 18px;">1、</span><!--[endif]--><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">郑重提醒用户注意本协议中免除</font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">责任和限制用户权利的条款，请用户仔细阅读，自主考虑风险。未成年人应在法定监护人的陪同下阅读本协议。</span></font><span style="font-size: 18px;"> </span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;mso-list:l4 level1 lfo9;"><!--[if !supportLists]--><span style="font-family: Calibri; font-size: 18px;">2、</span><!--[endif]--><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">本协议的效力、解释及纠纷的解决，适用于中华人民共和国法律。若用户和</font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">之间发生任何纠纷或争议，首先应友好协商解决，协商不成的，用户同意将纠纷或争议提交</font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><font face="宋体"><span style="font-size: 18px;">住所地有管辖权的人民法院管辖。</span></font><span style="font-size: 18px;"> </span></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" style="margin-left:10.5000pt;mso-para-margin-left:0.0000gd;mso-list:l4 level1 lfo9;"><!--[if !supportLists]--><span style="font-family: Calibri; font-size: 18px;">3、</span><!--[endif]--><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">本协议的任何条款无论因何种原因无效或不具可执行性，其余条款仍有效，对双方具有约束力。</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal" align="justify" style="mso-pagination:none;text-align:justify;text-justify:inter-ideograph;"><span style="font-family: Calibri; font-size: 18px;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal" align="justify" style="mso-pagination:none;text-align:justify;text-justify:inter-ideograph;"><span style="font-family: Calibri; font-size: 18px;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">本《协议》版权由</font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">所有，</font></span><span style="font-family: 宋体; font-size: 18px;"><font face="宋体">诚正</font></span><span style="font-family: Calibri; font-size: 18px;"><font face="宋体">保留一切对本《协议》解释的权利。</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:22.0000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p></div>',
  'share_image' => '',
  'register_url' => 'https://ntf1.iun.cc/h5',
  'award_rate' => '6',
  'level_rate' => '1',
  'first_rate' => '3',
  'second_rate' => '2',
  'ali_app_id' => '202100313664721',
  'ali_public_key' => 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkoprSDM8KxfQSka3Nju7KZIZmiwb5VKtC/dNPj8CW4i26NkQOgxb2VemH7U1uyl2M3N6RTVk7T/VBeJxlFPCUahBSMqfaKmlFYIJ06ALoJ2wNoPZGq0+DV0VIKpbtucIqoi2DdlWY/LeJaXIbSOTjigA1j4vUgvpIlT+aq4OEhPQq5MI1vvIacwjFprkmVJiF6zd8gmipFp0h47IEs1ryaSYhiqUMmZygAGs7emo/3V4eB8BoE9CgcZqyxFD9dQw7NHukQIHVvVS8bMNwDvTIvzJjiiiNhxIHCp2ah20yqCNE42MFrOFks/9019j2emgDMuhbQuiBpPw+VN1X5UmWwIDAQAB',
  'ali_private_key' => 'MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCP9mO22DeITvEK4byKbwLAXEthKt1kQvBYmwWJ7bNe9+eiQeh595sCgjXOdTOtX1ZX36fqL7guglg7URR7h0iSAMKQjUQ20ayBXZ8Gy8lOquu/6uke+o45w82g7v1FX+Fx5ggX+nOdzYO+mEcP4UeKlpw9v2x+YCwfQZJmzHwbNHzFmmmPPIK4DNJRNjOJFqhOESD1UJRg6PSPzm6Ipv6cE/NbI+vhoC1b9xjWaH+6rxtdCqSxxf1MKAufIApTruElWqulVFVa0J7OTKAIyZp4osPuGaEn0ZLAXKRRsruyb5FbQK4cjxo2BMkTGJsdif3K2RPJhlCevJwl/ECWlpATAgMBAAECggEBAIegSoTB4l9qb7Aexu9sch0jVmiuZ3DDl4cCVQ+CfxAjYXf9u7TcTo7oeSSOSic1wDR9IsaAOnammdUYJ8HQy8+xI5vnWrKCipA90Uonxvl0ETH3b7SdvEwzaZAKV1V6ZPxXCJz+eNnb+hgfgiM1y56HEZ8irmXI2QiBUBnE388IDrSF84LjjuZiMbVXqH+mgjKuJovHhfe2E6dV1sHovVVkHmTgXrbWYJKCiApk//5ET9aL3j89dSQQIH44JjBpkRUaIH8vmt8UBaUYxVzqFFURYlBOhdieenaa9Y+PiLeJWjQDW+Yp6vl81aNA+Q/DOqXNUBBWzgaTg77yL4H287ECgYEA5EHhu/YTXIyaPcPTWEE1MW0hJwaI1AP90dx90ntxdUS26nLtwhDcLzhYoZia6PGwhoHJhPuHDHWz+ZzQ7ny9vuyBWnfHoP57OW0dLZY/33gmgct1ERtyibBCJL2ElSUG1+gRvn9YWPLysfaxJLyRzEp7I+7jhK306/cFWT7Prt8CgYEAoXW2Z+MvIQDxkGZOTugwRPG0G2094VIhMozMSNyPBlfMAcNW8hFcNrDYYPr17Cbj1mW7t80mszN1J4S9f25bZZRxkgU48Obj9Xu6Z16t+v2s5ZdsdFrNEKeHPPiB8AY3CVF+EGepRUg++0n8Yy2twe3Lv2snv/w3pzefSFDK6U0CgYEAkqSg2ZjmJ3dNQJEmnnSGMBLkUaYpEczerIzzaN5VrflPaqAbj6o1S0Dv8CGSpEViG4gWZ5EQ2jhkP+E3eYA6hwZ6tBxv7EaR8/rd3APDVVZjps+Hjk4L79mFJQV8wDThiKRXggNeRwcOVLcgZ3GeWZkgM52uHfeEenRgw01PMBECgYEAjCCLNFJ5Xp1hCT+hCt58tflHpN4EbH9JDIQh78Jr5sdf6M/Nr7zdWSHWSSTFNjTyW+pjJrvHsJMiRC/x/pyaeeiBQIeDyZ+5jB3bw0bqnAB5g7ENkVYUzzV2K7ZJnzTloxK05CvzPovbDWBCyRilyr9Eq1amYvrUmi2t8acc06kCgYANeZwskFXWpEmE2g0bFROdwCFMDEos/GyMmuOn6DfifaQLkjQVpceOmxwJax3XH0+iypqmCObHpSJPO0iDRWiMAe1rKqFuMHDNxyAO6ndsZkpuIAZ9MLrLr3OxWRM6REDgMBsbtcPdO4qIF444ncB0Sa3BkqKczUFZOnu//DewDg==',
  'wx_app_id' => '',
  'wx_app_secret' => '',
  'wx_mch_id' => '1601187757',
  'wx_mch_key' => 'WXWaii86620712533023199005023116',
  'is_appoint' => '1',
  'shop_award_rate' => '2',
  'register_award_number' => '10',
  'total_award_number' => '10',
  'sales_order_number' => '1',
  'appoint_account' => '500',
  'rush_rule' => '1',
  'register_day' => '10',
  'register_premium_min_number' => '1',
  'register_premium_max_number' => '9',
  'premium_max_number' => '10',
  'sales_wholesale_rate' => '90',
  'sales_e_rate' => '10',
  'split_rule' => '2',
  'thirty_un_pay' => '50',
  'sixty_un_pay' => '100',
  'thirty_un_confirm' => '50',
  'gift_account' => '5000',
  'pay_time' => '60',
  'confirm_time' => '30',
  'server_url' => 'https://ntf1.iun.cc/h5',
  'ali_notify_url' => 'http://122.114.52.93:85/api/notify/aliNotify',
  'wx_small_app_id' => 'wx2735c9307fb2da47',
  'wx_small_app_secret' => 'cfdd1f0ae3fdbeaefea647c4be19ca3d',
  'wx_notify_url' => 'https://ntf1.iun.cc/api/notify/wxNotify',
  'conceal_content' => '<p class="MsoNormal" style="text-indent:21.0000pt;mso-char-indent-count:2.0000;"><br></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">一、注册协议条款的确认和接受</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">“</font></span><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">诚正</font></span><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">”（以下亦称“本应用”），隶属于</font></span><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">宜春藏文网络</font></span><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">科技有限公司。同意按照本协议的规定及其不定时发布的操作规则提供基于互联网和移动互联网的相关服务（以下称</font><font face="宋体">“网络服务”）。</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">为获得网络服务，申请人应当认真阅读、充分理解本《协议》中各条款，包括免除或者限制本应用责任的免责条款及对用户的权利限制条款。审慎阅读并选择接受或不接受本《协议》（未成年人应在法定监护人陪同下阅读）。</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">同意接受本协议的全部条款的，申请人应当按照页面上的提示完成全部的注册程序，并在注册程序过程中点击</font><font face="宋体">“同意”按钮，否则视为不接受本《协议》全部条款，申请人应当终止并退出申请。</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">本《协议》可由本应用定期更新，更新后的协议条款一旦公布即代替原来的协议条款，恕不再另行通知，用户可在本应用查阅最新版协议条款。在本应用修改《协议》条款后，如果用户不接受修改后的条款，请立即停止使用本应用提供的网络服务，继续使用的用户将被视为已接受了修改后的协议。</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">二、服务内容</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;">1、网络服务的具体内容由本应用根据实际情况提供，包括资讯、工具、社群。</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;">2、本应用提供的网络服务包括收费和免费。对于收费服务，本应用会在用户使用之前给予用户明确的提示，只有用户根据提示确认同意支付相关费用，用户才能使用该等收费服务。如用户未支付相关费用，则本应用有权不向用户提供该等收费服务。</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;">3、用户理解，本应用仅提供本应用明确承诺的网络服务，除此之外与相关网络服务有关的设备（如个人电脑、手机、及其他与接入互联网或移动网有关的装置）及所需的费用（如为接入互联网而支付的电话费及上网费、为使用移动网络而支付的手机费）均应由用户自行负担。</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">三、用户帐号</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;">1、经本应用注册系统完成注册程序并通过身份认证的用户即为正式用户。</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;">2、如发现用户帐号中含有不雅文字或不恰当名称的，本应用保留注销其用户帐号的权利。</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;">3、用户帐号的所有权归本应用，用户完成申请注册手续后，用户享有使用权。3个月未使用的用户账号，本应用保留收回的权利。</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;">4、用户有义务保证密码和帐号的安全，用户利用该帐号所进行的一切活动引起的任何损失或损害，由用户自行承担全部责任，本应用不承担任何责任。如用户发现帐号遭到未授权的使用或发生其他任何安全问题，应立即修改账号密码并妥善保管。因黑客行为或用户的保管疏忽导致帐号非法使用，本应用不承担任何责任。</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;">5、用户帐号和密码仅由初始申请注册人使用，用户不得将自己用户账户或密码有偿或无偿以转让、出借、授权等方式提供给第三人操作和使用，否则用户应当自行承担因违反此要求而遭致的任何损失。违反本项约定的，本应用并保留收回账号的权利。若因违反本约定对他人造成损害的，用户应与实际使用人承担连带赔偿责任，同时本应用保留追究用户违约责任的权利。</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;">6、用户帐号在丢失、遗忘密码及因合用产生使用权归属纠纷后，须遵照本应用的申诉途径请求找回帐号。用户可以凭初始注册资料向本应用申请找回帐号。本应用的账户恢复机制仅负责识别申请用户所提资料与系统记录资料是否一致，而无法识别申诉人是否系帐号的真正使用权人。对用户因被他人冒名申请而致的任何损失，本应用不承担任何责任，用户知晓帐号及密码保管责任在于用户，本应用并不承诺帐号丢失或遗忘密码后用户一定能通过申诉找回帐号。用户应当谨慎填写初始手机号或注册邮箱作为确认接收争议帐号的指定邮箱。</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;">7、本应用建议用户应当使用本人名义为用户账户充值或行使付款行为。若用户存在使用第三人的名义进行充值或付款，或委托第三人代为充值或付款之行为的，则以上行为被视作本人的行为，若由于该第三人行为导致充值或付款行为失败或成功后又被撤销的，均被认为是用户本人真实意思的表示和用户本人实施的行为，由此所造成的一切法律后果均由用户自行承担。</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">四、使用规则</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;">1、用户在使用本应用网络服务过程中，必须遵循国家的相关法律法规，不得发布危害国家安全、色情、暴力、侵犯版权等任何合法权利等非法内容;也不得利用本应用平台发布含有虚假、有害、胁迫、侵害他人隐私、骚扰、侵害、中伤、粗俗、或其它道德上令人反感的内容。</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;">2、本应用可依其合理判断，对违反有关法律法规或本协议约定;或侵犯、妨害、威胁任何人权利或安全的内容，或者假冒他人的行为，本应用有权停止传输任何前述内容，并有权依其自行判断对违反本条款的任何用户采取适当的法律行动，包括但不限于，隐匿和下架具有违法性、侵权性、不当性等内容，阻止其使用本应用全部或部分网络服务，并且依据法律法规保存有关信息并向有关部门报告等。</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;">3、对于经由本应用网络服务而传送的内容，本应用不保证前述内容的正确性、完整性或品质。用户在接受本服务时，有可能会接触到令人不快、不适当或令人厌恶的内容。在任何情况下，本应用均不对任何内容负责，包括但不限于任何内容发生任何错误或纰漏以及衍生的任何损失或损害。本应用有权（但无义务）自行拒绝或删除经由本应用网络服务提供的任何内容。用户使用上述内容，应自行承担风险。</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;">4、用户通过本应用网络服务所发布的任何内容并不反映本应用的观点或政策，本应用对此不承担任何责任。用户须对上述内容的真实性、合法性、无害性、有效性等全权负责，与用户所发布信息相关的任何法律责任由用户自行承担，与本应用无关。</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">五、版权声明</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">本应用中包含的任何文本、图片、图形、音频和</font>/或视频资料均受版权、商标和/或其它财产所有权法律的保护，未经相关权利人同意，上述资料均不得在任何媒体直接或间接发布、播放、出于播放或发布目的而改写或再发行，或者被用于其他任何商业目的。</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">六、隐私保护</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;">1、保护用户隐私是本应用的一项基本政策，本应用保证不对外公开或向第三方提供用户的注册资料及用户在使用网络服务时存储在本应用内的非公开内容，但下列情况除外:</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">（</font>1）事先获得用户的书面明确授权</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">（</font>2）根据有关的法律法规要求</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">（</font>3）按照相关政府主管部门的要求</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">（</font>4）为维护社会公众的利益</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">（</font>5）为维护本应用的合法权益</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;">2、为了更好地为用户提供全面服务，用户同意本应用可将用户注册资料及使用信息提供本应用关联公司使用。本应用保证前述关联公司同等级地严格遵循本协议第六条第1款之隐私保护责任。</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;">3、用户同意：本应用或本应用运营商的关联公司在必要时有权根据用户注册时或接受服务时所提供的联系信息（包括但不限于电子邮件地址、联系电话、联系地址、即时聊天工具账号等），通过电子邮件、电话、短信、邮寄、即时聊天、弹出页面等方式向用户发送如下信息：</span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">（</font>1）各类重要通知信息，可能包括但不限于订单、交易单、修改密码提示等重要信息。此类信息可能对用户的权利义务产生重大的有利或不利影响，用户务必及时关注。</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">（</font>2）商品和服务广告、促销优惠等商业性信息。若用户不愿意接收此类信息，则可通过告知（口头或书面）的方式通知本应用或本应用运营商的关联公司取消发送，亦可通过本应用或本应用运营商关联公司所提供的相应退订功能（若有）进行退订。</span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">七、协议的用途、更新和效力</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;">1、本协议之服务条款用以规范用户使用本应用提供的服务，本协议与本应用社区行为准则构成完整的协议。</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;">2、鉴于国家法律法规不时变化及本应用运营之需要，本应用有权对本协议条款不时地进行修改，修改后的协议一旦被公布于本应用上即告生效，并替代原来的协议。用户有义务不时关注并阅读最新版的协议及网站公告。如用户不同意更新后的协议，则应立即停止接受本应用依据本协议提供的服务；若用户继续使用本应用提供的服务的，即视为同意更新后的协议。如果本协议中任何一条被视为废止、无效或因任何理由不可执行，该条应视为可分的且并不影响任何其余条款的有效性和可执行性。</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p>&nbsp;</o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">八、联系方式</font></span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">当你有个人信息相关问题或其他的投诉、建议等，可以通过如下方式与本应用联系，本应用将尽快审核所涉及内容，并于</font>15个工作日内对于你的问题、投诉、建议进行回复；</span><span style="mso-spacerun:\'yes\';font-family:Calibri;mso-fareast-font-family:宋体;
mso-bidi-font-family:\'Times New Roman\';font-size:10.5000pt;mso-font-kerning:1.0000pt;"><o:p></o:p></span></p><p class="MsoNormal"><br></p><p class="MsoNormal"><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;"><font face="宋体">邮箱：</font></span><span style="mso-spacerun:\'yes\';font-family:宋体;font-size:13.5000pt;
mso-font-kerning:0.0000pt;">2369578566@qq.com</span></p>',
  'wx_small_notify_url' => 'https://ntf1.iun.cc/api/notify/wxSmallNotify',
  'buy_content' => '<p>抢购规则抢购规则抢购规则抢购规则抢购规则抢购规则抢购规则抢购规则抢购规则抢购规则抢购规则抢购规则<br></p>',
  'wx_image' => '/uploads/20220118/f0340570fa4c0a70cbc9e69ee5a1c6d9.png',
  'qq_iamge' => '/uploads/20220118/17928c3d43856f4dd216a14b4ef0b32e.png',
  'contact_phone_1' => '请扫二维码添加客服',
  'app_download' => '',
  '技术支持' => '',
  'zqh' => '',
  'about_content' => '<p>关于我们关于我们关于我们关于我们关于我们关于我们关于我们关于我们关于我们关于我们关于我们关于我们关于我们关于我们<br></p>',
  'douyi_image' => '/uploads/20220119/0fdf060dde128f30883787a795ee2b08.jpg',
  'is_trade' => '1',
  'trade_day' => '0',
  'rule' => '<p><br></p>',
  'sub_commission' => '0',
  'wx_appid' => 'wxf377897cb24c13b1',
  'wx_appsecret' => 'aab2fa561577aa86a90290885486cdc1',
  'wx_notifyurl' => 'https://ntf1.iun.cc/api/notify/wxGzhNotify',
  'host' => 'https://nft.cyrxljk.cn/',
  'appcode' => '8e474886a78a4fc3a7d6f8396025f5a8',
  'apiKey' => '42e2F0N8K1S7Z0C5A1O5E0C8H4c967Zj',
  'apiSecret' => 'A2s200e8w1O7Z0Q5M1v5K0M8D4Z9x7eZ',
  'url' => 'https://apis.avata.bianjie.ai/',
  'status' => '1',
  'account' => 'iaa1n3h04g6rdx9rtv36gc5q7wesdz0rprhdxj3env',
  'names' => '诚正数藏平台',
  'yxgtime' => '60',
  '$site.contact_phone_2' => '',
  'amount_proportion' => '10',
  'xgstatus' => '20',
  'mhxgstatus' => '100',
  'mh_gmsm' => '数字藏品为虚拟数字商品，而非实物，仅限实名认证为年满14周岁的中国大陆用户购买。数字藏品的版权由发行方或原创者拥有，除另行取得版权拥有者书面同意外，不得将数字藏品用于任何商业用途，不支持退换。本商品源文件不支持本地下载。请勿对数字藏品进行炒作、场外交易、欺诈，或以任何其他非法方式进行使用',
  'buy_ri_handle' => '1',
  'instructions' => '<p>数字藏品为虚拟数字商品，而非实物，仅限实名认证为年满14周岁的中国大陆用户购买。数字藏品的版权由发行方或原创者拥有，除另行取得版权拥有者书面同意外，不得将数字藏品用于任何商业用途，不支持退换。本商品源文件不支持本地下载。请勿对数字藏品进行炒作、场外交易、欺诈，或以任何其他非法方式进行使用</p>',
);
