(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/uni-footer/uni-footer"],{"2ad0":function(t,e,n){"use strict";(function(t){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var n={props:{background:{type:String,default:""},currentTab:{type:String,default:""}},data:function(){return{list:[{pagePath:"../index/index",iconPath:"../../static/img/footer/index.png",selectedIconPath:"../../static/img/footer/indexh.png",text:"首页"},{pagePath:"../index/secondHand",iconPath:"../../static/img/footer/market.png",selectedIconPath:"../../static/img/footer/marketh.png",text:"寄售"},{pagePath:"../manghe/index",iconPath:"../../static/img/footer/manghe.png",selectedIconPath:"../../static/img/footer/mangheh.png",text:"盲盒"},{pagePath:"../my/my",iconPath:"../../static/img/footer/my.png",selectedIconPath:"../../static/img/footer/myh.png",text:"我的"}],rank:null}},methods:{switchNav:function(e,n){0!=this.rank||1!=e?e!=this.currentTab&&(console.log(n.pagePath),t.redirectTo({url:n.pagePath})):this.toast("市场暂没有开放")}},mounted:function(){this.rank=t.getStorageSync("rank")}};e.default=n}).call(this,n("543d")["default"])},"778d":function(t,e,n){"use strict";var a=n("f53e"),o=n.n(a);o.a},"9fc9":function(t,e,n){"use strict";n.r(e);var a=n("d43e"),o=n("b8f2");for(var i in o)"default"!==i&&function(t){n.d(e,t,(function(){return o[t]}))}(i);n("778d");var c,r=n("f0c5"),u=Object(r["a"])(o["default"],a["b"],a["c"],!1,null,"89d1ed7a",null,!1,a["a"],c);e["default"]=u.exports},b8f2:function(t,e,n){"use strict";n.r(e);var a=n("2ad0"),o=n.n(a);for(var i in a)"default"!==i&&function(t){n.d(e,t,(function(){return a[t]}))}(i);e["default"]=o.a},d43e:function(t,e,n){"use strict";var a;n.d(e,"b",(function(){return o})),n.d(e,"c",(function(){return i})),n.d(e,"a",(function(){return a}));var o=function(){var t=this,e=t.$createElement;t._self._c},i=[]},f53e:function(t,e,n){}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/uni-footer/uni-footer-create-component',
    {
        'components/uni-footer/uni-footer-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("9fc9"))
        })
    },
    [['components/uni-footer/uni-footer-create-component']]
]);
